# Generated by Django 2.2.12 on 2020-05-23 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200519_1928'),
        ('teachers', '0004_auto_20200520_1149'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='headman',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student'),
        ),
    ]
