# Generated by Django 2.2.12 on 2020-05-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200523_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Teacher'),
        ),
    ]
