# Generated by Django 2.2.12 on 2020-05-19 16:28

from django.db import migrations


def forwards(apps, schema):
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all().only('first_name', 'last_name').iterator():
        student.first_name = str.capitalize(student.first_name)
        student.last_name = str.capitalize(student.last_name)
        student.save(update_fields=['first_name', 'last_name'])


def backwards(apps, schema):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_phone'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
