# Generated by Django 2.2.12 on 2020-05-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_logger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
